/**
 * Crypto Market Agent implemented with LangChain and OpenAI
 */
import {
  TaskContext,
  A2AServer,
  TaskYieldUpdate,
  schema
} from "@agenticdao/crypto-a2a-server";
import config from "./config";
import { cryptoMarketAgent } from "./agent";
import { AIMessage, BaseMessage, isAIMessage } from "@langchain/core/messages";

/**
 * Crypto Market Agent implementation using LangChain and OpenAI
 */
async function* cryptoMarketAgentHandler({
  task,
  userMessage,
  history,
}: TaskContext): AsyncGenerator<TaskYieldUpdate, schema.Task | void, unknown> {
  // Make sure we have a user message
  if (!userMessage || !userMessage.parts.length) {
    console.warn(`[CryptoMarketAgent] No user message found for task ${task.id}`);
    yield {
      state: "failed",
      message: {
        role: "agent",
        parts: [{ type: "text", text: "No input message found." }],
      },
    };
    return;
  }

  // Get the user's query from the message
  const userQuery = userMessage.parts.find(part => part.type === 'text')?.text || '';
  
  if (!userQuery.trim()) {
    yield {
      state: "input-required",
      message: {
        role: "agent",
        parts: [{ type: "text", text: "Please provide a cryptocurrency to analyze. For example: 'Analyze Bitcoin market trends' or 'What's the current status of Ethereum?'" }],
      },
    };
    return;
  }

  // Provide initial status update
  yield {
    state: "working",
    message: {
      role: "agent",
      parts: [{ type: "text", text: "Analyzing cryptocurrency market data..." }],
    },
  };

  try {
    // Run the crypto market agent graph with the user's query
    const result = await cryptoMarketAgent.invoke(userQuery);
    
    // Get the last assistant message
    const assistantMessage = result.messages
      .filter((msg: BaseMessage) => isAIMessage(msg))
      .pop() as AIMessage;
    
    if (!assistantMessage) {
      throw new Error("No response generated by the agent");
    }
    
    // Process AIMessage content, which might be string or complex content type
    let messageContent = "";
    if (typeof assistantMessage.content === 'string') {
      messageContent = assistantMessage.content;
    } else if (Array.isArray(assistantMessage.content)) {
      // Process complex content type, extract text portions
      messageContent = assistantMessage.content
        .map(item => {
          if (typeof item === 'string') return item;
          if (item.type === 'text') return item.text;
          return '';
        })
        .join('');
    }
    
    // Prepare the message parts
    const messageParts: schema.Part[] = [];
    
    // Add crypto data as a data part if available
    if (result.crypto_data) {
      if (result.crypto_data.error) {
        // If there's an error, add the error information
        messageParts.push({
          type: "text",
          text: `\n\nError: ${result.crypto_data.error}\n${result.crypto_data.details || ''}`
        });
        
        // Return input-required state
        yield {
          state: "input-required",
          message: {
            role: "agent",
            parts: messageParts,
          },
        };
        return;
      } else if (result.crypto_data.success) {
        // Add successful crypto market data
        messageParts.push({
          type: "data",
          data: result.crypto_data
        });
        
        // If there's formatted info, add a friendlier display
        if (result.crypto_data.formatted && result.crypto_data.formatted.message) {
          messageParts.push({
            type: "text",
            text: `\n\n${result.crypto_data.formatted.message}`
          });
        }
      }
    }

    messageParts.push({
      type: "text",
      text: messageContent,
    });

    for (let i = 0; i < messageParts.length; i++) {
      yield {
        index: i,
        name: `crypto market analysis ${i}`,
        parts: [messageParts[i]],
        lastChunk: i === messageParts.length - 1,
      };
    }
    
    // Check if the message content indicates more input is needed
    const needsMoreInput = messageContent.includes("need more information") || 
                         messageContent.includes("please provide") || 
                         messageContent.includes("missing") ||
                         messageContent.includes("specify");
    
    // Return the final response
    yield {
      state: needsMoreInput ? "input-required" : "completed",
      message: {
        role: "agent",
        parts: messageParts,
      },
    };
  } catch (error) {
    // Handle errors
    console.error("[CryptoMarketAgent] Error processing request:", error);
    yield {
      state: "failed",
      message: {
        role: "agent",
        parts: [
          {
            type: "text", 
            text: `Error processing your request: ${error instanceof Error ? error.message : String(error)}`
          }
        ],
      },
    };
  }
}

// Agent card definition
const cryptoMarketAgentCard: schema.AgentCard = {
  name: "Crypto Market Analysis Agent",
  description: "Provides comprehensive cryptocurrency market analysis",
  url: `http://${config.server.host}:${config.server.port}`,
  provider: {
    organization: "A2A Samples",
  },
  version: "0.1.0",
  capabilities: {
    streaming: true,
    pushNotifications: false,
    stateTransitionHistory: true,
  },
  authentication: null,
  defaultInputModes: ["text", "text/plain"],
  defaultOutputModes: ["text", "text/plain"],
  skills: [
    {
      id: "analyze_crypto_markets",
      name: "Cryptocurrency Market Analysis Tool",
      description:
        "Provides detailed analysis of cryptocurrency markets including current prices, trends, historical context, and future outlook",
      tags: ["cryptocurrency", "market analysis", "crypto trading", "bitcoin", "ethereum"],
      examples: [
        "Analyze Bitcoin's current market situation", 
        "What's the market outlook for Ethereum?",
        "How is Solana performing in the market?",
        "Current price and trend analysis for Cardano"
      ],
    },
  ],
};

// Create and start the server
const server = new A2AServer(cryptoMarketAgentHandler, {
  card: cryptoMarketAgentCard,
  enableVerification: true,
});

// Start the server on the configured port
server.start(config.server.port);

console.log(`[Crypto Market Agent] Server started on http://${config.server.host}:${config.server.port}`);
console.log("[Crypto Market Agent] Press Ctrl+C to stop the server");